# diese Action soll das grundsätzliche Script testen
name: PS7CompatibiltyCheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #  branches: [ "master" ]
  # pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: PC7CompatibilityRules laden und auf Repository anwenden
        env:
          Platform: ${{ matrix.platform }}
        run: |
          Install-Module -Name PSScriptAnalyzer -Force
          git clone https://github.com/janestreet/PS7CompatibilityRules.git
          Invoke-ScriptAnalyzer -Path '.' -Recurse -CustomRulePath .\PS7CompatibilityRules\*.psm1
          
