name: Test Install-7Zip

on:
  workflow_dispatch:

jobs:
  test-7zip:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            os: windows-2025
            is64: true
            isArm: false
            sleep-seconds: 60

          - name: x86
            os: windows-2025
            is64: false
            isArm: false
            sleep-seconds: 30
            
          - name: arm64
            os: windows-11-arm
            is64: true
            isArm: true
            sleep-seconds: 1

    runs-on: ${{ matrix.os }}

    name: Test ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # startet das Installationsscript
      - name: Installationsscript ausführen
        run: |
          C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoExit -NoProfile -Command '& {$s=(Invoke-WebRequest -UseBasicParsing -Uri https://raw.githubusercontent.com/Delapro/DelaproInstall/master/DLPInstall.PS1).Content.Replace([string][char]10,[char]13+[char]10); $s=$s.SubString(0, $s.IndexOf(''CMDLET-ENDE'')); $tempPath = ''C:\temp''; $scriptPath=Join-Path -Path $tempPath -ChildPath easy.PS1; If (-Not (Test-Path $tempPath)) {md $tempPath} ; Set-Content -path $scriptPath -value $s; cd $tempPath; powershell.exe -NoExit -NoProfile -executionPolicy Bypass -File $scriptPath }'
      
      - name: Install-7Zip ausführen
      
        shell: pwsh
        run: |
          C:
          cd \temp
          . .\easy.PS1
          # 32-Bit Unterstützung simulieren, "false" kommt von matrix.is64 vom yaml-File
          function Test-64Bit { return [bool]::Parse("${{ matrix.is64 }}") }
          Start-Sleep -Seconds ${{ matrix.sleep-seconds }}  # um Timeout beim Download in den verschiedenen Runnern zu umgehen
          Install-7Zip -Verbose

          "Validierung"
          $exe = @(
            "${env:ProgramFiles}\7-Zip\7z.exe",
            "${env:ProgramFiles(x86)}\7-Zip\7z.exe"
          ) | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1

          if (-not $exe) {
            throw "7-Zip wurde nicht installiert!"
          }

          Write-Host "Gefunden: $exe"

          & "$exe" i | Select-Object -First 20
