name: Test Install-7Zip

on:
  workflow_dispatch:

jobs:
  test-7zip:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            os: windows-2025
            is64: true
            isArm: false

          - name: x86
            os: windows-2025
            is64: false
            isArm: false

          - name: arm64
            os: windows-11-arm
            is64: true
            isArm: true

    runs-on: ${{ matrix.os }}

    name: Test ${{ matrix.name }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      - name: Run Install-7Zip
      
        shell: pwsh
        run: |
          C:
          cd \temp
          . .\easy.PS1
          Install-7Zip

          # Validierung
          $paths = @(
            "${env:ProgramFiles}\7-Zip\7z.exe",
            "${env:ProgramFiles(x86)}\7-Zip\7z.exe"
          ) | Where-Object { $_ -and (Test-Path $_) }

          if (-not $paths) {
            throw "7-Zip wurde nicht installiert!"
          }

          $exe = $paths[0]
          Write-Host "Gefunden: $exe"

          & $exe i | Select-Object -First 20
