name: Test Install-7Zip

on:
  workflow_dispatch:

jobs:
  test-7zip:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x64
            os: windows-2025
            is64: true
            isArm: false

          - name: x86
            os: windows-2025
            is64: false
            isArm: false

          - name: arm64
            os: windows-11-arm
            is64: true
            isArm: true

    runs-on: ${{ matrix.os }}

    name: Test ${{ matrix.name }}

    steps:
      - name: Run Install-7Zip
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          # Architektur simulieren
          function Test-64Bit { return [bool]::Parse("${{ matrix.is64 }}") }
          function Test-Arm64 { return [bool]::Parse("${{ matrix.isArm }}") }

          Function Install-7Zip {
            [CmdletBinding()]
            Param(
              [System.String]$tempDirectory = "$Env:TEMP\"
            )

            $Version = '2600'
            If (Test-64Bit) {
              If (Test-Arm64) {
                $url = "https://www.7-zip.org/a/7z$($Version)-arm64.exe"
                $Dest = "$($tempDirectory)\7z$($Version)-arm64.exe"
                $Sha256 = '92FAC666911336F3BBF3D99FDC48EC36FE20AC7A4200556936E61A8076AE6493'
              } else {
                $url = "https://www.7-zip.org/a/7z$($Version)-x64.exe"
                $Dest = "$($tempDirectory)\7z$($Version)-x64.exe"
                $Sha256 = '6FE18D5B3080E39678CABFA6CEF12CFB25086377389B803A36A3C43236A8A82C'
              }
            } else {
              $url = "https://www.7-zip.org/a/7z$($Version).exe"
              $Dest = "$($tempDirectory)\7z$($Version).exe"
              $Sha256 = 'D605EB609AA67796DCA7CFE26D7E28792090BB8048302D6E05EDE16E8E33145C'
            }

            Write-Host "Download: $url"
            Start-BitsTransfer -Source $url -Destination $Dest

            $hash = (Get-FileHash -Path $Dest -Algorithm SHA256).Hash
            Write-Host "SHA256: $hash"

            if ($hash -ne $Sha256) {
              throw "Hash stimmt nicht!"
            }

            Write-Host "Starte Silent-Installation..."
            Start-Process -Wait -FilePath $Dest -ArgumentList "/S"
          }

          Install-7Zip

          # Validierung
          $paths = @(
            "${env:ProgramFiles}\7-Zip\7z.exe",
            "${env:ProgramFiles(x86)}\7-Zip\7z.exe"
          ) | Where-Object { $_ -and (Test-Path $_) }

          if (-not $paths) {
            throw "7-Zip wurde nicht installiert!"
          }

          $exe = $paths[0]
          Write-Host "Gefunden: $exe"

          & $exe i | Select-Object -First 20
